config/routes.rb
Rails.application.routes.draw do
  resources :posts do
  	resources :comments
  end
  resources :subscribers

  get 'posts/index'

# root 'posts#index'

get 'promo', to: 'promo#index'
get 'about', to: 'about#index'

root 'promo#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
validates :name, :presence => true
validates :title, :presence => true,
:length => { :minimum => 5 }
mount_uploader :image, ImageUploader
has_many :comments, :dependent => :destroy
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:commenter, :body))
		redirect_to post_path(@post)
	end
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
      respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
    	params.require(:post).permit(:name, :title, :author1, :content, :image)
    end
  
end

app/controllers/promo_controller.rb
class PromoController < ApplicationController
  def index
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
    @subscribers = Subscriber.all
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      redirect_to about_path, notice: "Ура!"
    else
      redirect_to about_path, notice: "Не ура("
    end
  end

  private

    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<% if notice %>
  <%= notice %>
<% end %>
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>
<%= link_to "Blog", posts_path %>
<h2>Узнать раньше всех о запуске проекта:</h2>
<%= render "subscribers/form" %>

app/views/comments/_comment.html.erb
<p>
	<b>Commenter:</b>
	<%= comment.commenter %>
</p>
<p>
	<b>Comment:</b>
	<%= comment.body %>
</p>
<p>
	<b>Commenter:</b>
	<%= comment.commenter %>
</p>
<p>
	<b>Comment:</b>
	<%= comment.body %>
</p>
<p>
	<%= link_to 'Destroy Comment', [comment.post, comment],
								:confirm => 'Are you sure?',
								:method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<div class="field">
		<%= f.label :commenter %><br />
		<%= f.text_field :commenter %>
	</div>
	<div class="field">
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</div>
		<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
	<%= form.label :image %>
	<%= form.file_field :image %>
</div>

  <div class="field">
	<%= form.label :author1 %>
	<%= form.text_field :author1 %>
</div>

 <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

<div class="actions">
    <%= form.submit %>
  </div>

  <% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Author</th>
      <th>Content</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.author1 %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>
<%= link_to(image_tag(@post.image.thumb.url, alt: 'Image'), @post.image.url, target: '_blank') if @post.image? %>
<br>
<%= link_to(image_tag(@post.image.small_thumb.url, alt: 'Image'), @post.image.url, target: '_blank') if @post.image? %>
<br>
<%= image_tag(@post.image.url, alt: 'Image') if @post.image? %>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
	<strong>Author:</strong>
	<%= @post.author1 %>
</p>
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>
<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/promo/index.html.erb
<h1>Promo#index</h1>
<p>Find me in app/views/promo/index.html.erb</p>
<%= link_to "About", about_path %>

app/views/subscribers/_form.html.erb
<% @subscriber = Subscriber.new %>
<%= form_for @subscriber do |f|%>
  <%= f.email_field :email, placeholder: "Email" %>
  <%= f.submit "Пыщ!"%>
<% end %>

app/views/welcome/_counter.html.erb
<h1> <%= counter %>
</h1>

app/views/welcome/index.html.erb
<% counter = 1 %>
<% 3.times do %> <%= render 'counter', counter: counter %> <% counter += 1 %>
<% end %>
<h1>Ваше программирование!</h1>